export const PythonCourses = [
  {
    cname: "Course 100: Introduction to Python Programming",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "5+ Grade",
    mode: "Online",
    price: 800,
    open: 1,
    topics: [
      "Basic Python syntax and grammar",
      "Basic code debugging",
      "Translating abstract ideas into code",
      "Basic problem-solving with lists and loops",
    ],
  },
  {
    cname: "Course 101: Algorithms and Data Structures in Python",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "5+ Grade",
    mode: "Online",
    price: 900,
    open: 1,
    topics: [
      "Mastering Python programming language",
      "Proficiency in built-in data structures",
      "Developing skills in designing functions",
      "Simplifying complex problems",
    ],
  },
  {
    cname: "Course 102V: Python Hands-on Projects",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "5+ Grade",
    mode: "Online",
    price: 1200,
    open: 0,
    topics: [
      "Project 1: Personal Finance Tracker",
      "Project 2: Simple Web Scraper",
      "Project 3: Basic Chatbot",
      "Project 4: Game Development",
    ],
  },
  {
    cname: "Course 102P: Python Hands-on Projects",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "5+ Grade",
    mode: "In Person",
    price: 2000,
    open: 0,
    topics: [
      "Project 1: Personal Finance Tracker",
      "Project 2: Simple Web Scraper",
      "Project 3: Basic Chatbot",
      "Project 4: Game Development",
    ],
  },
];

export const BronzeCourses = [
  {
    cname: "Course 200: Problem Decomposition with Iteration & Recursion",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "6+ Grade",
    mode: "Online",
    price: 1100,
    open: 1,
    topics: [
      "Iteration and bottom-up problem solving",
      "Recursion and top-down problem solving",
      "Problem decomposition",
      "Divide and conquer: Merge sort",
    ],
  },
  {
    cname: "Course 201: Depth First Search In-Depth",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "6+ Grade",
    mode: "Online",
    price: 1100,
    open: 0,
    topics: [
      "Advanced recursion",
      "Depth First Search (DFS)",
      "Floodfill Algorithm",
      "Backtracking",
      "Advanced applications of DFS",
    ],
  },
  {
    cname: "Course 202: Breadth First Search In-Depth",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "6+ Grade",
    mode: "Online",
    price: 1100,
    open: 0,
    topics: [
      "Python standard libraries: set, dict, queue",
      "Breadth First Search (BFS)",
      "DFS vs. BFS comparison and state graph concepts",
      "General search strategies",
      "Advanced techniques: pruning",
      "Advanced usage of Python containers",
    ],
  },
];

export const SilverCourses = [
  {
    cname: "Course 300: Advanced Algorithm Design I",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "7+ Grade",
    mode: "Online",
    price: 1200,
    open: 0,
    topics: [
      "Mastery of Python language",
      "Time complexity",
      "Binary Search",
      "Sorting algorithms",
      "Two Pointers",
      "Greedy Algorithm",
      "Asymptotic analysis of sorting algorithms",
    ],
  },
  {
    cname: "Course 301: Advanced Data Structures I",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "7+ Grade",
    mode: "Online",
    price: 1200,
    open: 0,
    topics: [
      "Tree representation and basic properties",
      "Graph representation and basic properties",
      "Binary Search Tree",
      "Shortest path problems",
      "Tree traversal",
      "Minimum Spanning Tree",
      "Heap and Hash Table",
    ],
  },
  {
    cname: "Course 302: Dynamic Programming I",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "7+ Grade",
    mode: "Online",
    price: 1200,
    open: 0,
    topics: [
      "Understanding Dynamic Programming",
      "Basic concepts of memoization",
      "Basic concepts of tabulation",
      "Classic dynamic programming problems",
      "DP optimizations intuitions and techniques",
    ],
  },
];

export const GoldCourses = [
  {
    cname: "Course 400: Advanced Algorithm Design II",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "8+ Grade",
    mode: "Online",
    price: 1300,
    open: 0,
    topics: [
      "Sorting review",
      "Other methods of sorting",
      "Greedy algorithms",
      "Prefix sums and modifications of prefix sums",
      "Divide and conquer",
      "Advanced Binary Search",
    ],
  },
  {
    cname: "Course 401: Advanced Data Structures II",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "8+ Grade",
    mode: "Online",
    price: 1300,
    open: 0,
    topics: [
      "Linear data structures: stacks and queues",
      "Sliding windows",
      "Monotonic stacks/queues and applications",
      "Linked lists",
      "Hashing, hash tables, and applications of hashing",
      "Advanced applications of hashing, string hashing",
      "Miscellaneous data structures practice",
    ],
  },
  {
    cname: "Course 402: Dynamic Programming II",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "8+ Grade",
    mode: "Online",
    price: 1300,
    open: 0,
    topics: [
      "Introduction to pull/push DP",
      "More tree DP, solving for all roots",
      "DAG DP",
      "Bitmask DP, digit DP, and range DP",
      "Counting DP",
      "Miscellaneous DP problems practice",
    ],
  },
];

export const AIFutureCourses = [
  {
    cname: "Course 500: Introduction to Machine Learning",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "9+ Grade",
    mode: "Online",
    price: 1400,
    open: 0,
    topics: [
      "Introduction to machine learning",
      "Basic concepts of model training and testing",
      "Introduction to NumPy, pandas, and Matplotlib",
      "Data visualization",
      "Practice problems and projects",
    ],
  },
  {
    cname: "Course 501: Deep Learning with PyTorch",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "9+ Grade",
    mode: "Online",
    price: 1400,
    open: 0,
    topics: [
      "Introduction to deep learning",
      "PyTorch basics",
      "Building neural networks with PyTorch",
      "Advanced PyTorch techniques",
      "Model evaluation and deployment",
      "Practice problems and projects",
    ],
  },
];

export const FastLaneCourses = [
  {
    cname: "Course 600V: Intern Foundation Preparation I",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "10+ Grade",
    mode: "Online",
    price: 1500,
    open: 1,
    topics: [
      "Introduction to internship preparation I",
      "Module 1: Review of Python",
      "Module 2: Review of machine learning",
      "Module 3: Review of deep learning",
      "Practical projects combining all skills",
    ],
  },
  {
    cname: "Course 600P: Intern Foundation Preparation I",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "10+ Grade",
    mode: "In Person",
    price: 3000,
    open: 1,
    topics: [
      "Introduction to internship preparation I",
      "Module 1: Review of Python",
      "Module 2: Review of machine learning",
      "Module 3: Review of deep learning",
      "Practical projects combining all skills",
    ],
  },
  {
    cname: "Course 601V: Intern Handson Project Preparation II",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "10+ Grade",
    mode: "Online",
    price: 1500,
    open: 0,
    topics: [
      "Internship project preparation",
      "Module 1: Comprehensive Python Review",
      "Module 2: Business Projects",
      "Module 3: Science Projects",
      "Module 4: Math and Statistics Projects",
      "Module 5: Machine Learning Projects",
      "Module 6: Medical Projects",
    ],
  },
  {
    cname: "Course 601P: Intern Handson Project Preparation II",
    duration: "13 Weeks",
    dates: "September 1st - November 30th",
    lang: "Python",
    class: "10+ Grade",
    mode: "In Person",
    price: 3000,
    open: 0,
    topics: [
      "Internship project preparation",
      "Module 1: Comprehensive Python Review",
      "Module 2: Business Projects",
      "Module 3: Science Projects",
      "Module 4: Math and Statistics Projects",
      "Module 5: Machine Learning Projects",
      "Module 6: Medical Projects",
    ],
  },
];

export const FallCourses = {
  "Python Courses": [
    {
      cname: "Course 100: Introduction to Python Programming",
      duration: "13 Weeks",
      dates: "September 1st - November 30th",
      lang: "Python",
      class: "5+ Grade",
      mode: "Online",
      price: 800,
      open: 1,
      topics: [
        "Basic Python syntax and grammar",
        "Basic code debugging",
        "Translating abstract ideas into code",
        "Basic problem-solving with lists and loops",
      ]
    },
    {
      cname: "Course 101: Algorithms and Data Structures in Python",
      duration: "13 Weeks",
      dates: "September 1st - November 30th",
      lang: "Python",
      class: "5+ Grade",
      mode: "Online",
      price: 800,
      open: 1,
      topics: [
        "Mastering Python programming language",
        "Proficiency in built-in data structures",
        "Developing skills in designing functions",
        "Simplifying complex problems",
      ],
    },
  ],
  "USACO—USACO Bronze Knowledge": [
    {
      cname: "Course 200: Problem Decomposition with Iteration & Recursion",
      duration: "13 Weeks",
      dates: "September 1st - November 30th",
      lang: "Python",
      class: "6+ Grade",
      mode: "Online",
      price: 1000,
      open: 1,
      topics: [
        "Iteration and bottom-up problem solving",
        "Recursion and top-down problem solving",
        "Problem decomposition",
        "Divide and conquer: Merge sort",
      ],
    },
  ],

  "Intern Fastlane Courses": [
    {
      cname: "Course 600: Intern Foundation Preparation I",
      duration: "13 Weeks",
      dates: "September 1st - November 30th",
      lang: "Python",
      class: "10+ Grade",
      mode: "Online",
      price: 2000,
      open: 1,
      topics: [
        "Introduction to internship preparation I",
        "Module 1: Review of Python",
        "Module 2: Review of machine learning",
        "Module 3: Review of deep learning",
        "Practical projects combining all skills",
      ],
    },
  ],
};
